/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JPanel;
import javax.swing.UIManager;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import java.io.File;

import javax.swing.JFileChooser;


/**
 *
 * @author Gisa
 */
public class Pdf_Viewer extends javax.swing.JInternalFrame {

    public Pdf_Viewer() {
        try {
            for(UIManager.LookAndFeelInfo info: UIManager.getInstalledLookAndFeels())
            if("Windows".equals(info.getName())){
                UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        initComponents();
        
        
    }
    
    
    void openPdf(String file){
        try {
            SwingController control=new SwingController();
            SwingViewBuilder viewBuilder=new SwingViewBuilder(control);
            JPanel viewPanel=viewBuilder.buildViewerPanel();
            ComponentKeyBinding.install(control, viewPanel);
            control.getDocumentViewController().setAnnotationCallback(
                    new org.icepdf.ri.common.MyAnnotationCallback(
                    control.getDocumentViewController()));
            control.openDocument(file);
            scrollPane.setViewportView(viewPanel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        pdfViewerButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("PDF Viewer");

        scrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.SW_RESIZE_CURSOR));

        pdfViewerButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        pdfViewerButton.setText("Choose a PDF file");
        pdfViewerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfViewerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 509, Short.MAX_VALUE)
                .addComponent(pdfViewerButton))
            .addComponent(scrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pdfViewerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pdfViewerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfViewerButtonActionPerformed
        JFileChooser fileChooser=new JFileChooser();
                fileChooser.showOpenDialog(null);
                File f=fileChooser.getSelectedFile();
                String fileName=f.getAbsolutePath();
                openPdf(fileName);
                    
    }//GEN-LAST:event_pdfViewerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pdfViewerButton;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    
}
